### ISSUE TITLE
Launcher: TclError: unknown option "-state" (OSX only?)

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#274] opened 2015-02-09 17:54 UTC
2 Mac OSX users tried installing oTree with the launcher as follows:

- Download and unzip: https://github.com/oTree-org/otree-launcher/archive/master.zip
- run otree.sh

They got this traceback:

```
Cleaning temp dir '/Users/som/.otree-launcher/temp'
Opening log file '/Users/som/.otree-launcher/launcher.log'...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "otree_launcher/gui.py", line 419, in run
    frame = OTreeLauncherFrame(root)
  File "otree_launcher/gui.py", line 189, in init
    self.refresh_deploy_path()
  File "otree_launcher/gui.py", line 231, in refresh_deploy_path
    self.deploy_menu.entryconfig(1, state=state)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 2729, in entryconfigure
    return self._configure(('entryconfigure', index), cnf, kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1253, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-state"
```

**Comment by leliel12** [comment] 2015-02-09 20:41
Give some days to install osx on avirtual machine

**Comment by leliel12** [comment] 2015-02-11 17:06
i fail on install macosx on virtualbox. 

The idea on this change disable this menu
![menu_007](https://cloud.githubusercontent.com/assets/299010/6151664/126afd74-b1f6-11e4-8bc1-dc03edd5dc0d.png)

if the internal virtualenv is still not created.

**WARNING** The stack trace attached in the issue is from previous version because the line of the bug is not *231*. The new line is *226*

Also if you want to detect if the code is running inside mac osx please add a constant to *cons.py* with the next code

```python!

IS_OSX = sys.platform.startswith("darwin")

```
more info: http://stackoverflow.com/questions/8220108/how-do-i-check-the-operating-system-in-python

**Comment by leliel12** [comment] 2015-02-28 15:03
closed in

https://github.com/oTree-org/otree-launcher/commit/57de4e6ce8cdecc771041e43a4698b46a2c85a3d

**Closed by leliel12** 2015-02-28 15:03 UTC
Labels: consultant
