### ISSUE TITLE
'Template' object has no attribute 'nodelist' when creating MTurk Session

### ISSUE THREAD

**Issue by jsteinhart** [oTree-org/otree-core#396] opened 2015-10-03 13:04 UTC
I'm running OTree from master on my fork, which is up-to-date at 67f368cd8e309bbbd4c5c4d9082dcb6db4074063 and uses otree-core 0.3.45

I run it on Heroku, and attempt to create a session for any builtin app (e.g. "Public goods"), and get [this error](http://dpaste.com/2D3P1JR).

I get the same error using my own app and a custom preview_template, so I would venture a guess that the problem is in otree-core (although I guess it could be an error in the "official" apps/templates which I also make in my app!). Some Googling for the error message brings up discussions (e.g. [this](https://github.com/funkybob/formulation/issues/37)) which refer to changes in Django 1.8's template behavior, but I have no idea if/how this is relevant here since I am a Django dilettante!

**Comment by oTree-org** [comment] 2015-10-05 17:22
I can reproduce this. Repro steps:

In the admin interface you need to click "Sessions". The button "Create new session" has a down-arrow; click that and you will see "For MTurk". Then select any of the listed games, and specify a number of users and click create.

**Comment by jsteinhart** [comment] 2015-10-08 05:52
Do you have any idea when the last time was that this worked? If you don't already know the cause of this, and could suggest a known-good starting point, I could try a git bisect search for the offending commit if it would help!

**Comment by alexsanduk** [comment] 2015-10-08 06:10
I have disabled template validation for Mturk session in f390fbedea8a2703897dc4aaa606ba6af109aead. Will enable it again when I fix the bug.

**Comment by oTree-org** [comment] 2015-10-08 06:53
Thanks, I published 0.3.48 with this change.

**Comment by gregmuellegger** [comment] 2015-12-07 10:41
I have pushed a fix for the next_button validation to `master`. I have not re-enabled the MTurk validation yet in the views, please test first if everything is the way you want it.

I think the test as it is written now might give false positives when there is actually a next button in the page but "hidden" inside a `{% with %}` statement or any other template tag. We have already discussed in the past that these kinds of checks are a little brittle. Are you aware of this?

**Comment by oTree-org** [comment] 2015-12-07 13:07
Yes I am aware, I think it's OK, because we just display a warning, not an error. Another false positive is when the page doesn't use our {% next_button %} tag, but instead used a custom <button> element. However, maybe I will make the text of the warning more clear for users.

**Closed** 2016-01-01 05:28 UTC
