### ISSUE TITLE
Need separate base templates for admin pages vs. participant pages

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#302] opened 2015-04-10 16:13 UTC
Currently, all oTree pages (admin pages and participant pages) inherit from `otree/templates/BaseBuiltIn.html`. We would be better off splitting into two separate base templates so that they can diverge according to their separate needs. For example:

* admin pages have a black header menu but participant pages do not.
* participant pages should contain the "missing fields" (formfield_is_missing) warning but admin pages should not
* participant pages always contain a form with the same general schema/structure, but this structure should not be imposed on admin pages.

So, I think some refactoring/cleanup should be done on `BaseBuiltIn.html` and `FormPage.html` (`FormPage` refers to an ordinary participant page).

**Comment by alexsanduk** [comment] 2015-05-12 14:01
The issue is closed in 4567dfc16172de208d877d975a595e681ec37dfe

**Closed by alexsanduk** 2015-05-12 14:01 UTC
Labels: consultant
